version: '3.8'
services:
  ratings:
    build: ./ratings
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://ratings:ratingspass@mongodb:27017/ratings
  mongodb:
    image: bitnami/mongodb:4.4.2-debian-10-r0
    volumes:
      - "./ratings/databases:/docker-entrypoint-initdb.d"
    environment:
      MONGODB_ROOT_PASSWORD: rootpass
      MONGODB_USERNAME: ratings
      MONGODB_PASSWORD: ratingspass
      MONGODB_DATABASE: ratings
  details:
    build: ./details
    ports: 
      - 9080:9080
  reviews:
    build: ./reviews
    ports: 
      - 9000:9000
    environment:
      ENABLE_RATINGS: true
      RATINGS_SERVICE: http://ratings:8080
  productpage:
    build: ./productpage
    ports: 
      - 3000:3000
    environment:
      DETAILS_HOSTNAME: http://details:9080
      RATINGS_HOSTNAME: http://ratings:8080
      REVIEWS_HOSTNAME: http://reviews:9000
